
(
SELECT CONCAT('ALTER DATABASE ',`SCHEMATA`.`SCHEMA_NAME`,' CHARACTER SET `utf8mb4` COLLATE `utf8mb4_unicode_520_ci`;') AS TO_CHANGE
FROM `information_schema`.`SCHEMATA`
WHERE SCHEMA_NAME = "<DATABASE_NAME>" 
AND (DEFAULT_CHARACTER_SET_NAME <> 'utf8mb4' OR DEFAULT_COLLATION_NAME <> 'utf8mb4_unicode_520_ci')
)
UNION ALL
(
SELECT CONCAT_WS(' ',
	CONCAT('ALTER TABLE ',TABLE_SCHEMA,'.`',TABLE_NAME,'` ENGINE = MYISAM DEFAULT CHARSET= utf8mb4 COLLATE= utf8mb4_unicode_520_ci PAGE_CHECKSUM=0, ROW_FORMAT=DYNAMIC;'),
	CONCAT('ALTER TABLE ',TABLE_SCHEMA,'.`',TABLE_NAME,'` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;'),
	CONCAT('OPTIMIZE TABLE ',TABLE_SCHEMA,'.`',TABLE_NAME,'`;')
)
FROM information_schema.`TABLES`
WHERE TABLE_SCHEMA = "<DATABASE_NAME>"
AND TABLE_TYPE='BASE TABLE'
AND (`TABLE_COLLATION` <> 'utf8mb4_unicode_520_ci'
OR	`ENGINE` <> 'MYISAM'
)
ORDER BY TABLE_SCHEMA, `TABLE_NAME`);

